name: CI

on:
  push:
  pull_request:

jobs:
  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-ci

      - name: Run Ktlint
        run: ./gradlew ktlintCheck --no-daemon

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-ci

      - name: Run tests
        run: ./gradlew test --no-daemon --build-cache
